### ISSUE TITLE
What would it take to create a REPL?

### ISSUE THREAD

**Issue by mdbergmann** [dmcoles/EVO#10]
there is `Eval` already, but no 'Read' that could turn a string into code.
A REPL should allow to dynamically load modules.

**Comment by dmcoles** [comment]
I don't believe this is feasible. I'm not very familiar with REPL but it seems it would need an interpreter. Amiga E is compiled and has no interpreting capability. There is no way to perform an evaluation of an arbitrary string.

**Comment by mdbergmann** [comment]
Common Lisp is also compiled and has a REPL. But I don't know what it takes to do it.
Thanks for answering.
