### ISSUE TITLE
Misaligned writes in ac structure in graphics/gels.e

### ISSUE THREAD

**Issue by SamuraiCrow** [dmcoles/EVO#2]
http://aminet.net/package/dev/e/Gels020 corrects this on 020+.  Please include.  (I am the author of the package listed above.)

**Comment by dmcoles** [comment]
Just for my clarification, are you asking me to include your ac020 object and the GET_AC(x) macro into graphics/gels.e or to include the whole gels020.e file into the graphics folder?

**Comment by SamuraiCrow** [comment]
Either would be fine.  All I added was a pad-word to the beginning (though I probably should have made it a private field) so that the longwords and pointers would align to 4-byte increments.

**Comment by dmcoles** [comment]
thanks, ive added those into gels.e
