### ISSUE TITLE
Optimizing for lower calling overhead

### ISSUE THREAD

**Issue by SamuraiCrow** [dmcoles/EVO#3]
https://github.com/EEC-Developers/eec/issues/25 describes an optimization where the first pass of the compiler could keep track of which registers are used by a function and save only the non-scratch members of the register list to the stack in the function preamble and restore the same list at the end.  Since it's 68k series only, I thought I'd mention it here also.

**Comment by dmcoles** [comment]
I don't believe this issue affects e-vo

**Comment by dmcoles** [comment]
.

**Comment by dmcoles** [comment]
I don't believe this issue affects e-vo
