### ISSUE TITLE
Missing tutorial in guide

### ISSUE THREAD

**Issue by Jonson26** [dmcoles/EVO#6]
The beginners guide by Jason Hulance mentioned in E-VO.guide is not in the docs folder

**Comment by dmcoles** [comment]
This is correct. It is included in the original Amiga E archive http://aminet.net/package/dev/e/amigae33a. Also this may contain the same information http://cshandley.co.uk/JasonHulance/

I will look into including this in future releases as well

**Comment by dmcoles** [comment]
the beginners guide is also available from the aminet http://aminet.net/package/dev/e/BeginnersGuideUpd

i am not sure that including it with each release of E-VO is necessary when it is already available in various forms.

I will update the guide so with a reference to the aminet package to clarify the situation
